# Generated by Django 4.1.3 on 2022-11-22 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_cred',
            fields=[
                ('U_Id', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('Password', models.CharField(max_length=30)),
                ('R_Id', models.IntegerField()),
            ],
        ),
    ]
