# Generated by Django 4.1.3 on 2022-12-01 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelDesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_details',
            fields=[
                ('H_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('H_Name', models.CharField(max_length=30)),
                ('Free_Room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Id', models.IntegerField()),
                ('Floor_Id', models.IntegerField()),
                ('Room_Id', models.IntegerField()),
                ('Status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_allocation_h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Id', models.IntegerField()),
                ('Floor_Id', models.IntegerField()),
                ('Room_Id', models.IntegerField()),
                ('Roll_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('Name', models.CharField(max_length=40)),
                ('Roll_No', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('Gender', models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('Course', models.CharField(max_length=100)),
                ('Ph_No', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('P_Name', models.CharField(max_length=40)),
                ('P_Ph_No', models.BigIntegerField()),
            ],
        ),
    ]
