# Generated by Django 4.1.3 on 2022-12-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelDesk', '0002_hostel_details_room_details_student_allocation_h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_details',
            fields=[
                ('Course_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='Course',
        ),
        migrations.AddField(
            model_name='student_details',
            name='Course_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HostelDesk.course_details'),
        ),
    ]
