# Generated by Django 4.1.3 on 2022-12-02 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelDesk', '0003_course_details_remove_student_details_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess_details',
            fields=[
                ('M_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('M_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mess_manager',
            fields=[
                ('Mm_Id', models.IntegerField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('Name', models.CharField(max_length=40)),
                ('M_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostelDesk.mess_details')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_manager',
            fields=[
                ('Hm_Id', models.IntegerField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('Name', models.CharField(max_length=50)),
                ('H_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostelDesk.hostel_details')),
            ],
        ),
    ]
