# Generated by Django 4.1.3 on 2022-12-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostelDesk', '0004_mess_details_mess_manager_hostel_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess_manager',
            name='M_Id',
        ),
        migrations.DeleteModel(
            name='Mess_details',
        ),
        migrations.DeleteModel(
            name='Mess_manager',
        ),
    ]
