# Generated by Django 4.1.3 on 2022-12-03 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelDesk', '0005_remove_mess_manager_m_id_delete_mess_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_manager',
            name='Hm_Id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
