# Generated by Django 4.1.3 on 2022-12-03 15:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelDesk', '0006_alter_hostel_manager_hm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess_details',
            fields=[
                ('M_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('M_Name', models.CharField(max_length=50)),
                ('Allocated', models.IntegerField()),
                ('Capacity', models.IntegerField()),
                ('Accepted_Gender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_allocation_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Id', models.IntegerField()),
                ('Roll_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mess_manager',
            fields=[
                ('Mm_Id', models.IntegerField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('Name', models.CharField(max_length=40)),
                ('M_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostelDesk.mess_details')),
            ],
        ),
    ]
